DROP DATABASE IF EXISTS envios_paquetes;
-- Crear la base de datos
CREATE DATABASE envios_paquetes;
USE envios_paquetes;

-- Crear la tabla Sucursal
CREATE TABLE SUCURSAL (
    COD_SUCURSAL INT NOT NULL PRIMARY KEY,
    DIRECCION VARCHAR(100),
    TELEFONOS VARCHAR(20)
);

-- Crear la tabla Empleado
CREATE TABLE EMPLEADO (
    COD_EMPLEADO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COD_SUCURSAL INT,
    NOMBRE VARCHAR(100) DEFAULT 'EMPLEADO SIN NOMBRE',
    APELLIDO VARCHAR(100),
    DOMICILIO VARCHAR(100),
    TELEFONOS VARCHAR(20)
);

-- Crear la tabla Automovil
CREATE TABLE AUTOMOVIL (
    COD_AUTOMOVIL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COD_SUCURSAL INT,
    COD_EMPLEADO INT,
    PATENTE VARCHAR(20),
    MODELO VARCHAR(100)    
);

-- Crear la tabla Cliente
CREATE TABLE CLIENTE (
    COD_CLIENTE INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    DOMICILIO VARCHAR(100),
    TELEFONOS VARCHAR(20)
);

-- Crear la tabla Paquete
CREATE TABLE PAQUETE (
    COD_PAQUETE INT NOT NULL PRIMARY KEY,
    COD_CLIENTE INT,
    COD_EMPLEADO INT,
    FECHA_ENVIO DATE,
    ESTADO BOOLEAN
  );

-- Crear la tabla Producto
CREATE TABLE PRODUCTO (
    COD_PRODUCTO INT NOT NULL PRIMARY KEY,
    COD_PAQUETE INT,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(255),
    PESO DECIMAL(10 , 2 ),
    PRECIO DECIMAL(10 , 2 )
   );
   
-- Crear la tabla para almacenar los cambios de estado de los paquetes
CREATE TABLE LOG_CAMBIOS_PAQUETE (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    COD_PAQUETE INT,
    FECHA_CAMBIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO_ANTERIOR BOOLEAN,
    ESTADO_ACTUAL BOOLEAN
);


ALTER TABLE PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO_PAQUETE
    FOREIGN KEY (COD_PAQUETE) REFERENCES PAQUETE (COD_PAQUETE);

-- FOREIGN KEYS DEFINITION
ALTER TABLE EMPLEADO
	ADD CONSTRAINT FK_EMP_SUCURSAL
    FOREIGN KEY (COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL); 
    
ALTER TABLE AUTOMOVIL
	ADD CONSTRAINT FK_AUTO_SUCURSAL
	FOREIGN KEY (COD_SUCURSAL) REFERENCES SUCURSAL (cod_sucursal);
    
ALTER TABLE AUTOMOVIL
	ADD CONSTRAINT FK_AUTO_EMPLEADO
	FOREIGN KEY (COD_EMPLEADO) REFERENCES EMPLEADO (COD_EMPLEADO);
    
ALTER TABLE PAQUETE
	ADD CONSTRAINT FK_PAQUETE_CLIENTE
	FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE);
    
ALTER TABLE PAQUETE
	ADD CONSTRAINT FK_PAQUETE_EMPLEADO
	FOREIGN KEY (COD_EMPLEADO) REFERENCES EMPLEADO (COD_EMPLEADO);